language: ruby
rvm:
- 2.2.5

script: ./_script/cibuild

# branch whitelist, only for GitHub Pages
branches:
  only:
  - devel

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
