title: Settis
brief-intro: 
baseurl: ""
url: "https://settis.github.io"

permalink: /:year/:month/:day/:title/

# other links
github_username:  Settis
email: strannik.anton@gmail.com
vk_username: settis

# description_footer: 本站记录我前端之旅的沿途风景！

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
# duoshuo_shortname: #hygblog
# disqus_shortname: gaohaoyang

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
# baidu_tongji_id: cf8506e0ef223e57ff6239944e5d46a4
# google_analytics_gtag: G-9HKX561QKW

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 10

exclude: [vendor, Gemfile, Gemfile.lock, LICENSE, README.md]
plugins:
  - jekyll-paginate

defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
