title: Settis
brief-intro: 
baseurl: ""
url: "https://settis.github.io"

permalink: /:year/:month/:day/:title/

# other links

#facebook_username: gaohaoyang.water
github_username:  Settis
email: strannik.anton@gmail.com
vk_username: settis

# description_footer: 本站记录我前端之旅的沿途风景！

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
# duoshuo_shortname: #hygblog
# disqus_shortname: gaohaoyang

# statistic analysis 
google_analytics_id: UA-85517469-1

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# url
category_dir: category/
tag_dir: tag/

# paginate
gems: [jekyll-paginate]
paginate: 6

exclude: [vendor, Gemfile, Gemfile.lock, LICENSE, README.md]

defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
