#!/usr/bin/env bash
set -e # halt script on error

export JEKYLL_ENV=production
bundle exec jekyll build
time bundle exec htmlproofer ./_site --check-html

commit_message=`git log --format=%s -n 1`

git clone -b master "https://${GH_REF}" ghPages
rm -rf ghPages/*
cp -r _site/* ghPages/

cd ghPages

if [[ $(git status --porcelain 2> /dev/null | grep -v feed.xml | tail -n1) != "" ]]; then
  git add -A
  git config user.name "Travis-CI"
  git config user.email "travis@no.reply"
  git commit -m "$commit_message"
  git push "https://${GH_TOKEN}@${GH_REF}" > /dev/null 2>&1
fi
