#!/usr/bin/env bash
set -e # halt script on error

export JEKYLL_ENV=production
bundle exec jekyll build
bundle exec htmlproofer ./_site

commit_message=`git log --format=%s -n 1`

cd ../

git clone -b master "https://${GH_REF}" ghPages
rm -rf ghPages/**/*
cp -r settis.github.io/_site/* ghPages/

cd ghPages

if [[ $(git status --porcelain 2> /dev/null | tail -n1) != "" ]]; then
  git add -A
  git config user.name "Travis-CI"
  git config user.email "travis@no.reply"
  git commit -m "$commit_message"
  git push "https://${GH_TOKEN}@${GH_REF}" > /dev/null 2>&1
fi
